-- SDDE Core Baseline Migration
-- Supported Platforms: PostgreSQL, Oracle, MS SQL Server (ANSI SQL compliant)

-- 1. Permissions Table
CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

-- 2. Roles Table
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

-- 3. Role Permissions Join Table
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_perm FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- 4. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    full_name VARCHAR(150),
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- 5. User Roles Join Table
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- 6. SDLC Phases Table
CREATE TABLE sdlc_phases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT pk_sdlc_phases PRIMARY KEY (id)
);

-- 7. SDLC Deliverables Table
CREATE TABLE sdlc_deliverables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    phase_id BIGINT NOT NULL,
    CONSTRAINT pk_sdlc_deliverables PRIMARY KEY (id),
    CONSTRAINT fk_sdlc_deliv_phase FOREIGN KEY (phase_id) REFERENCES sdlc_phases(id) ON DELETE CASCADE
);

-- 8. Documents Table
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(50) NOT NULL,
    owner_id BIGINT NOT NULL,
    deliverable_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_documents PRIMARY KEY (id),
    CONSTRAINT fk_documents_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_documents_deliv FOREIGN KEY (deliverable_id) REFERENCES sdlc_deliverables(id)
);

-- 9. Document Versions Table
CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT NOT NULL,
    version_number VARCHAR(50) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    file_size BIGINT,
    content_type VARCHAR(150),
    created_by_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    change_summary VARCHAR(500),
    CONSTRAINT pk_document_versions PRIMARY KEY (id),
    CONSTRAINT fk_doc_vers_doc FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_vers_creator FOREIGN KEY (created_by_id) REFERENCES users(id)
);

-- 10. Document Metadata Table
CREATE TABLE document_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_version_id BIGINT NOT NULL UNIQUE,
    author VARCHAR(150),
    security_classification VARCHAR(100),
    keywords VARCHAR(255),
    department VARCHAR(100),
    language VARCHAR(50),
    CONSTRAINT pk_document_metadata PRIMARY KEY (id),
    CONSTRAINT fk_doc_meta_version FOREIGN KEY (document_version_id) REFERENCES document_versions(id) ON DELETE CASCADE
);

-- 11. Approval Workflows Table
CREATE TABLE approval_workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    initiated_by_id BIGINT NOT NULL,
    initiated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT pk_approval_workflows PRIMARY KEY (id),
    CONSTRAINT fk_app_wf_doc FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_wf_init FOREIGN KEY (initiated_by_id) REFERENCES users(id)
);

-- 12. Workflow Steps Table
CREATE TABLE workflow_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workflow_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    approver_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    actioned_at TIMESTAMP,
    comments VARCHAR(1000),
    CONSTRAINT pk_workflow_steps PRIMARY KEY (id),
    CONSTRAINT fk_wf_step_wf FOREIGN KEY (workflow_id) REFERENCES approval_workflows(id) ON DELETE CASCADE,
    CONSTRAINT fk_wf_step_appr FOREIGN KEY (approver_id) REFERENCES users(id)
);

-- 13. Workflow Histories Table
CREATE TABLE workflow_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workflow_id BIGINT NOT NULL,
    action VARCHAR(100) NOT NULL,
    actor_id BIGINT NOT NULL,
    actioned_at TIMESTAMP NOT NULL,
    comments VARCHAR(1000),
    CONSTRAINT pk_workflow_histories PRIMARY KEY (id),
    CONSTRAINT fk_wf_hist_wf FOREIGN KEY (workflow_id) REFERENCES approval_workflows(id) ON DELETE CASCADE,
    CONSTRAINT fk_wf_hist_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

-- 14. Audit Logs Table
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100),
    entity_id BIGINT,
    details VARCHAR(2000),
    ip_address VARCHAR(45),
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

-- 15. System Configurations Table
CREATE TABLE system_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    config_key VARCHAR(150) NOT NULL UNIQUE,
    config_value VARCHAR(1000) NOT NULL,
    description VARCHAR(255),
    updated_by VARCHAR(100),
    updated_at TIMESTAMP,
    CONSTRAINT pk_system_config PRIMARY KEY (id)
);
